---
name: "myjob"
fs:
  url: "/usr/share/fscrawler/data"
  update_rate: "1m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: true
  raw_metadata: false
  xml_support: false
  index_folders: false
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://elasticsearch:9200"
  username: "elastic"
  password: "changeme"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
